// Copyright 2015 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	metrics.proto

It has these top-level messages:
	MetricValue
	MetricPoint
	Empty
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type MetricValue struct {
	IntValue   int64   `protobuf:"varint,1,opt,name=IntValue" json:"IntValue,omitempty"`
	FloatValue float64 `protobuf:"fixed64,2,opt,name=FloatValue" json:"FloatValue,omitempty"`
	MetricType string  `protobuf:"bytes,3,opt,name=MetricType" json:"MetricType,omitempty"`
	ValueType  string  `protobuf:"bytes,4,opt,name=ValueType" json:"ValueType,omitempty"`
}

func (m *MetricValue) Reset()                    { *m = MetricValue{} }
func (m *MetricValue) String() string            { return proto1.CompactTextString(m) }
func (*MetricValue) ProtoMessage()               {}
func (*MetricValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MetricValue) GetIntValue() int64 {
	if m != nil {
		return m.IntValue
	}
	return 0
}

func (m *MetricValue) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *MetricValue) GetMetricType() string {
	if m != nil {
		return m.MetricType
	}
	return ""
}

func (m *MetricValue) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

type MetricPoint struct {
	Name      string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value     *MetricValue               `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Tags      map[string]string          `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MetricPoint) Reset()                    { *m = MetricPoint{} }
func (m *MetricPoint) String() string            { return proto1.CompactTextString(m) }
func (*MetricPoint) ProtoMessage()               {}
func (*MetricPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MetricPoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricPoint) GetValue() *MetricValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MetricPoint) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *MetricPoint) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterType((*MetricValue)(nil), "proto.MetricValue")
	proto1.RegisterType((*MetricPoint)(nil), "proto.MetricPoint")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MetricPlugin service

type MetricPluginClient interface {
	WriteMetricsPoint(ctx context.Context, in *MetricPoint, opts ...grpc.CallOption) (*Empty, error)
}

type metricPluginClient struct {
	cc *grpc.ClientConn
}

func NewMetricPluginClient(cc *grpc.ClientConn) MetricPluginClient {
	return &metricPluginClient{cc}
}

func (c *metricPluginClient) WriteMetricsPoint(ctx context.Context, in *MetricPoint, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.MetricPlugin/WriteMetricsPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MetricPlugin service

type MetricPluginServer interface {
	WriteMetricsPoint(context.Context, *MetricPoint) (*Empty, error)
}

func RegisterMetricPluginServer(s *grpc.Server, srv MetricPluginServer) {
	s.RegisterService(&_MetricPlugin_serviceDesc, srv)
}

func _MetricPlugin_WriteMetricsPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricPoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricPluginServer).WriteMetricsPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MetricPlugin/WriteMetricsPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricPluginServer).WriteMetricsPoint(ctx, req.(*MetricPoint))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetricPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MetricPlugin",
	HandlerType: (*MetricPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteMetricsPoint",
			Handler:    _MetricPlugin_WriteMetricsPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}

func init() { proto1.RegisterFile("metrics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xd9, 0x26, 0xfd, 0xff, 0xcd, 0xa4, 0x82, 0x0e, 0x1e, 0x4a, 0x28, 0x1a, 0x7a, 0xca,
	0x69, 0x2b, 0x11, 0xb1, 0x78, 0xaf, 0xe0, 0x41, 0x90, 0xa5, 0xe8, 0x79, 0x2b, 0x6b, 0x08, 0x26,
	0xd9, 0x90, 0x6c, 0x84, 0x3c, 0x81, 0xaf, 0xeb, 0x23, 0x48, 0x67, 0xb7, 0x69, 0xc4, 0x53, 0x66,
	0xbe, 0xef, 0xcb, 0xce, 0x6f, 0x06, 0x4e, 0x4b, 0x65, 0x9a, 0xfc, 0xad, 0xe5, 0x75, 0xa3, 0x8d,
	0xc6, 0x29, 0x7d, 0xa2, 0xab, 0x4c, 0xeb, 0xac, 0x50, 0x2b, 0xea, 0x76, 0xdd, 0xfb, 0xca, 0xe4,
	0xa5, 0x6a, 0x8d, 0x2c, 0x6b, 0x9b, 0x5b, 0x7e, 0x31, 0x08, 0x9f, 0xe8, 0xcf, 0x17, 0x59, 0x74,
	0x0a, 0x23, 0x38, 0x79, 0xac, 0x0c, 0xd5, 0x73, 0x16, 0xb3, 0xc4, 0x13, 0x43, 0x8f, 0x97, 0x00,
	0x0f, 0x85, 0x96, 0xce, 0x9d, 0xc4, 0x2c, 0x61, 0x62, 0xa4, 0xec, 0x7d, 0xfb, 0xd4, 0xb6, 0xaf,
	0xd5, 0xdc, 0x8b, 0x59, 0x12, 0x88, 0x91, 0x82, 0x0b, 0x08, 0x28, 0x48, 0xb6, 0x4f, 0xf6, 0x51,
	0x58, 0x7e, 0x0f, 0x24, 0xcf, 0x3a, 0xaf, 0x0c, 0x22, 0xf8, 0x95, 0x2c, 0x2d, 0x45, 0x20, 0xa8,
	0xc6, 0x04, 0xa6, 0x9f, 0xc3, 0xf0, 0x30, 0x45, 0xbb, 0x04, 0x1f, 0x2d, 0x20, 0x6c, 0x00, 0xd7,
	0x10, 0x0c, 0xab, 0x12, 0x4a, 0x98, 0x46, 0xdc, 0x1e, 0x83, 0x1f, 0x8e, 0xc1, 0xb7, 0x87, 0x84,
	0x38, 0x86, 0xf1, 0x1a, 0x7c, 0x23, 0xb3, 0x76, 0xee, 0xc7, 0x5e, 0x12, 0xa6, 0x8b, 0x5f, 0x23,
	0x88, 0x8c, 0x6f, 0x65, 0xd6, 0x6e, 0x2a, 0xd3, 0xf4, 0x82, 0x92, 0xd1, 0x1d, 0x04, 0x83, 0x84,
	0x67, 0xe0, 0x7d, 0xa8, 0xde, 0x51, 0xef, 0x4b, 0xbc, 0x18, 0x43, 0x07, 0x0e, 0xf0, 0x7e, 0xb2,
	0x66, 0xcb, 0xff, 0x30, 0xdd, 0x94, 0xb5, 0xe9, 0xd3, 0x0d, 0xcc, 0xdc, 0x80, 0xa2, 0xcb, 0xf2,
	0x0a, 0x6f, 0xe1, 0xfc, 0xb5, 0xc9, 0x8d, 0xb2, 0x62, 0xeb, 0x0e, 0xf2, 0x17, 0x25, 0x9a, 0x39,
	0x8d, 0x9e, 0xd9, 0xfd, 0xa3, 0xe6, 0xe6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x42, 0x4a, 0x17, 0xd3,
	0x0c, 0x02, 0x00, 0x00,
}
