// Copyright 2015 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	EventPoint
	Empty
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type EventPoint struct {
	Event     string                     `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Tags      map[string]string          `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *EventPoint) Reset()                    { *m = EventPoint{} }
func (m *EventPoint) String() string            { return proto1.CompactTextString(m) }
func (*EventPoint) ProtoMessage()               {}
func (*EventPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EventPoint) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EventPoint) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *EventPoint) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*EventPoint)(nil), "proto.EventPoint")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EventPlugin service

type EventPluginClient interface {
	WriteEventsPoint(ctx context.Context, in *EventPoint, opts ...grpc.CallOption) (*Empty, error)
}

type eventPluginClient struct {
	cc *grpc.ClientConn
}

func NewEventPluginClient(cc *grpc.ClientConn) EventPluginClient {
	return &eventPluginClient{cc}
}

func (c *eventPluginClient) WriteEventsPoint(ctx context.Context, in *EventPoint, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.EventPlugin/WriteEventsPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EventPlugin service

type EventPluginServer interface {
	WriteEventsPoint(context.Context, *EventPoint) (*Empty, error)
}

func RegisterEventPluginServer(s *grpc.Server, srv EventPluginServer) {
	s.RegisterService(&_EventPlugin_serviceDesc, srv)
}

func _EventPlugin_WriteEventsPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventPoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventPluginServer).WriteEventsPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventPlugin/WriteEventsPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventPluginServer).WriteEventsPoint(ctx, req.(*EventPoint))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventPlugin",
	HandlerType: (*EventPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteEventsPoint",
			Handler:    _EventPlugin_WriteEventsPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}

func init() { proto1.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0x51, 0x5c, 0xb7, 0xf8, 0xdc, 0x21, 0x15, 0x1d, 0x8c, 0x3b, 0xd4, 0x64, 0xf2, 0x24,
	0x83, 0x33, 0x34, 0x74, 0x2c, 0x78, 0x2f, 0x22, 0xd0, 0x59, 0x01, 0x55, 0x88, 0xda, 0x92, 0xb1,
	0xce, 0x01, 0xbf, 0x60, 0x9f, 0xab, 0x48, 0xaa, 0x93, 0x21, 0x93, 0xf4, 0x1f, 0xdf, 0x7d, 0xfa,
	0x05, 0xb9, 0x3c, 0x4b, 0x83, 0x6c, 0x9c, 0x2c, 0x5a, 0x9a, 0x86, 0xa3, 0x7c, 0x55, 0xd6, 0xaa,
	0x5e, 0x36, 0x21, 0x9d, 0xe6, 0xef, 0x06, 0xf5, 0x20, 0x1d, 0x8a, 0x61, 0x8c, 0xdc, 0xee, 0x97,
	0x00, 0x74, 0x7e, 0xef, 0xd3, 0x6a, 0x83, 0xf4, 0x19, 0xd2, 0x60, 0x29, 0x48, 0x45, 0xea, 0x8c,
	0xc7, 0x40, 0x0f, 0x90, 0x5d, 0xf6, 0x8a, 0x4d, 0x45, 0xea, 0xbc, 0x2d, 0x59, 0x34, 0xb3, 0xd5,
	0xcc, 0x8e, 0x2b, 0xc1, 0xaf, 0x30, 0x6d, 0xe0, 0x0e, 0x85, 0x72, 0x45, 0x52, 0x25, 0x75, 0xde,
	0xbe, 0x44, 0x9a, 0x5d, 0x1f, 0x64, 0x47, 0xa1, 0x5c, 0x67, 0x70, 0x5a, 0x78, 0x00, 0xcb, 0x37,
	0xc8, 0x2e, 0x23, 0xba, 0x85, 0xe4, 0x47, 0x2e, 0xff, 0x5d, 0xfc, 0xd5, 0xf7, 0x3b, 0x8b, 0x7e,
	0x96, 0xa1, 0x45, 0xc6, 0x63, 0x78, 0xdf, 0x1c, 0xc8, 0xee, 0x01, 0xd2, 0x6e, 0x18, 0x71, 0x69,
	0x3f, 0x20, 0x8f, 0xfe, 0x7e, 0x56, 0xda, 0xd0, 0x3d, 0x6c, 0xbf, 0x26, 0x8d, 0x32, 0xcc, 0x5c,
	0xfc, 0xe5, 0xd3, 0x4d, 0x8f, 0xf2, 0x71, 0x1d, 0x79, 0xc7, 0xe9, 0x3e, 0x84, 0xfd, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xcb, 0x31, 0x37, 0xf3, 0x53, 0x01, 0x00, 0x00,
}
