#! /bin/bash

docker kill influxdb
docker rm influxdb

docker run -d \
	-p 8083:8083 \
  -p 8086:8086 \
    -p 8090:8090 \
    -p  8099:8099 \
    -v $PWD/run.sh:/run.sh \
  --name influxdb vish/k8s_influxdb
